export const bibleMetadata = {
  // 구약
  "창세": { full: "창세기", abbrev: "창세", protestantAbbrev: "창" },
  "탈출": { full: "탈출기", abbrev: "탈출", protestantAbbrev: "출" },
  "레위": { full: "레위기", abbrev: "레위", protestantAbbrev: "레" },
  "민수": { full: "민수기", abbrev: "민수", protestantAbbrev: "민" },
  "신명": { full: "신명기", abbrev: "신명", protestantAbbrev: "신" },
  "여호": { full: "여호수아기", abbrev: "여호", protestantAbbrev: "수" },
  "판관": { full: "판관기", abbrev: "판관", protestantAbbrev: "삿" },
  "룻": { full: "룻기", abbrev: "룻", protestantAbbrev: "룻" },
  "1사무": { full: "사무엘기 상권", abbrev: "1사무", protestantAbbrev: "삼상" },
  "2사무": { full: "사무엘기 하권", abbrev: "2사무", protestantAbbrev: "삼하" },
  "1열왕": { full: "열왕기 상권", abbrev: "1열왕", protestantAbbrev: "왕상" },
  "2열왕": { full: "열왕기 하권", abbrev: "2열왕", protestantAbbrev: "왕하" },
  "1역대": { full: "역대기 상권", abbrev: "1역대", protestantAbbrev: "대상" },
  "2역대": { full: "역대기 하권", abbrev: "2역대", protestantAbbrev: "대하" },
  "에즈": { full: "에즈라기", abbrev: "에즈", protestantAbbrev: "스" },
  "느헤": { full: "느헤미야기", abbrev: "느헤", protestantAbbrev: "느" },
  "토빗": { full: "토빗기", abbrev: "토빗", protestantAbbrev: "토" },
  "유딧": { full: "유딧기", abbrev: "유딧", protestantAbbrev: "유딧" },
  "에스": { full: "에스텔기", abbrev: "에스", protestantAbbrev: "에" },
  "1마카": { full: "마카베오기 상권", abbrev: "1마카", protestantAbbrev: "1마" },
  "2마카": { full: "마카베오기 하권", abbrev: "2마카", protestantAbbrev: "2마" },
  "욥": { full: "욥기", abbrev: "욥", protestantAbbrev: "욥" },
  "시편": { full: "시편", abbrev: "시편", protestantAbbrev: "시" },
  "잠언": { full: "잠언", abbrev: "잠언", protestantAbbrev: "잠" },
  "코헬": { full: "코헬렛", abbrev: "코헬", protestantAbbrev: "전" },
  "아가": { full: "아가", abbrev: "아가", protestantAbbrev: "아" },
  "지혜": { full: "지혜서", abbrev: "지혜", protestantAbbrev: "지" },
  "집회": { full: "집회서", abbrev: "집회", protestantAbbrev: "집" },
  "이사": { full: "이사야서", abbrev: "이사", protestantAbbrev: "사" },
  "예레": { full: "예레미야서", abbrev: "예레", protestantAbbrev: "렘" },
  "애가": { full: "애가", abbrev: "애가", protestantAbbrev: "애" },
  "바룩": { full: "바룩서", abbrev: "바룩", protestantAbbrev: "바" },
  "에제": { full: "에제키엘서", abbrev: "에제", protestantAbbrev: "겔" },
  "다니": { full: "다니엘서", abbrev: "다니", protestantAbbrev: "단" },
  "호세": { full: "호세아서", abbrev: "호세", protestantAbbrev: "호" },
  "요엘": { full: "요엘서", abbrev: "요엘", protestantAbbrev: "욜" },
  "아모스": { full: "아모스서", abbrev: "아모스", protestantAbbrev: "암" },
  "오바": { full: "오바드야서", abbrev: "오바", protestantAbbrev: "옵" },
  "요나": { full: "요나서", abbrev: "요나", protestantAbbrev: "욘" },
  "미카": { full: "미카서", abbrev: "미카", protestantAbbrev: "미" },
  "나훔": { full: "나훔서", abbrev: "나훔", protestantAbbrev: "나" },
  "하박": { full: "하바쿡서", abbrev: "하박", protestantAbbrev: "합" },
  "스바": { full: "스바니야서", abbrev: "스바", protestantAbbrev: "습" },
  "학개": { full: "학가이서", abbrev: "학개", protestantAbbrev: "학" },
  "스가": { full: "즈카르야서", abbrev: "스가", protestantAbbrev: "슥" },
  "말라": { full: "말라키서", abbrev: "말라", protestantAbbrev: "말" },
  
  // 신약
  "마태": { full: "마태오 복음서", abbrev: "마태", protestantAbbrev: "마" },
  "마르": { full: "마르코 복음서", abbrev: "마르", protestantAbbrev: "막" },
  "루카": { full: "루카 복음서", abbrev: "루카", protestantAbbrev: "눅" },
  "요한": { full: "요한 복음서", abbrev: "요한", protestantAbbrev: "요" },
  "사도": { full: "사도행전", abbrev: "사도", protestantAbbrev: "행" },
  "로마": { full: "로마 신자들에게 보낸 서간", abbrev: "로마", protestantAbbrev: "롬" },
  "1코린": { full: "코린토 신자들에게 보낸 첫째 서간", abbrev: "1코린", protestantAbbrev: "고전" },
  "2코린": { full: "코린토 신자들에게 보낸 둘째 서간", abbrev: "2코린", protestantAbbrev: "고후" },
  "갈라": { full: "갈라티아 신자들에게 보낸 서간", abbrev: "갈라", protestantAbbrev: "갈" },
  "에페": { full: "에페소 신자들에게 보낸 서간", abbrev: "에페", protestantAbbrev: "엡" },
  "필리": { full: "필리피 신자들에게 보낸 서간", abbrev: "필리", protestantAbbrev: "빌" },
  "콜로": { full: "콜로새 신자들에게 보낸 서간", abbrev: "콜로", protestantAbbrev: "골" },
  "1테살": { full: "테살로니카 신자들에게 보낸 첫째 서간", abbrev: "1테살", protestantAbbrev: "살전" },
  "2테살": { full: "테살로니카 신자들에게 보낸 둘째 서간", abbrev: "2테살", protestantAbbrev: "살후" },
  "1티모": { full: "티모테오에게 보낸 첫째 서간", abbrev: "1티모", protestantAbbrev: "딤전" },
  "2티모": { full: "티모테오에게 보낸 둘째 서간", abbrev: "2티모", protestantAbbrev: "딤후" },
  "티토": { full: "티토에게 보낸 서간", abbrev: "티토", protestantAbbrev: "딛" },
  "필레": { full: "필레몬에게 보낸 서간", abbrev: "필레", protestantAbbrev: "몬" },
  "히브": { full: "히브리인들에게 보낸 서간", abbrev: "히브", protestantAbbrev: "히" },
  "야고": { full: "야고보 서간", abbrev: "야고", protestantAbbrev: "약" },
  "1베드": { full: "베드로 첫째 서간", abbrev: "1베드", protestantAbbrev: "벧전" },
  "2베드": { full: "베드로 둘째 서간", abbrev: "2베드", protestantAbbrev: "벧후" },
  "1요한": { full: "요한 첫째 서간", abbrev: "1요한", protestantAbbrev: "요일" },
  "2요한": { full: "요한 둘째 서간", abbrev: "2요한", protestantAbbrev: "요이" },
  "3요한": { full: "요한 셋째 서간", abbrev: "3요한", protestantAbbrev: "요삼" },
  "유다": { full: "유다 서간", abbrev: "유다", protestantAbbrev: "유" },
  "묵시": { full: "요한 묵시록", abbrev: "묵시", protestantAbbrev: "계" }
};
